[mypy]
python_version = 3.12
strict = True
ignore_missing_imports = True
plugins = pydantic.mypy

[mypy-alembic.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-testcontainers.*]
ignore_missing_imports = True
